### ISSUE TITLE
Ability to import pre-rendered html notebooks from hardrive location (not url)

### ISSUE THREAD

**Issue by JulianSpagnuolo** [rstudio/radix#40]
Currently the import_post() function will only accept a url, simply using a file location "/User/Joe/path/to/notebook.html"  will not work.
This means that if I wanted to use a radix blog to create a lab notebook I would have to do all analysis inside of the Rproject set up for the blog.

**Comment by jjallaire** [comment]
This should be addressed with this commit: https://github.com/rstudio/radix/commit/3ce7fa17cf5c15476dc9b169f9de877c58209ddb

**Comment by JulianSpagnuolo** [comment]
The check_license parameter is ignored as it is not parsed by the underlying ```import_article``` function.
Also an error is given:
```
import_post(url="/Users/user/Documents/projects/test.html", check_license = FALSE)
Importing /Users/user/Documents/projects/test.html...
This article does not have a creative commons license. Import anyway? [Y/n]: Y
Error: $ operator is invalid for atomic vectors
```
also with the underlying function:
```
radix:::import_article(url="/Users/user/Documents/projects/test.html", check_license = FALSE, collection = "posts")
Importing /Users/user/Documents/projects/test.html...
Error: $ operator is invalid for atomic vectors
```

**Comment by jjallaire** [comment]
Thanks again for reporting. I just pushed a fix to the `check_license` issue.

Is the file `/Users/user/Documents/projects/test.html` a radix article or just a generic html document? If it's the latter then it wouldn't work (although the error message should be much better).

If it is a Radix article, I haven't been able to reproduce this error locally so it might be best if you could attach that file to this issue (or publish it somewhere e.g. RPubs) so that I can reproduce with exactly the file you are using.

**Comment by JulianSpagnuolo** [comment]
I rendered the file off as both a Notebook (prefix *.nb.html) and a radix article (prefix *.html). I was trying to import the latter.

Attached the test file (zipped w/ the .Rmd because github wont allow html attachments.
[test.zip](https://github.com/rstudio/radix/files/2454954/test.zip)

**Comment by jjallaire** [comment]
Okay, should be fixed here: https://github.com/rstudio/radix/commit/88337ace5b3787c56b574c6f7183c65e135421af

Thanks again for reporting!
