### ISSUE TITLE
width of center column and its position

### ISSUE THREAD

**Issue by saptarshiguha** [rstudio/radix#7]
Hello,
Thank you for creating this. it's very nice indeed. I do have two questions,

1) is there a way to change the width of the main text column? it would be nice if i could make it say 10-20% wider (and everything els changes accordingly)

2) can we make the text column left aligned, i.e. move the column to the left of the page rather than dead center?

Much thanks

**Comment by jjallaire** [comment]
To do this you need to use CSS grid (you can provide a custom stylesheet via the `css` YAML option). Here is where we establish the layout for 1000 pixels and higher (actually, there is another layout for > 1280 pixels which you'd potentially also need to tweak):

https://github.com/radixpub/radix-r/blob/master/inst/rmarkdown/templates/radix_article/resources/distill.html#L149-L176

There are 2 reasons that the center column is narrow:

1) Ergonomics of reading are much better with a narrow column (one of the reasons that newspapers use narrow columns). See also medium.com layout upon which Radix was to some extent based: https://medium.freecodecamp.org/how-to-write-bulletproof-code-in-go-a-workflow-for-servers-that-cant-fail-10a14a765f22

2) To leave some room in the margin for asides and figures.

**Comment by saptarshiguha** [comment]
I agree a narrow column is more readable than a wide one, but i would like mine to fit in a few extra (maybe 3-4) words at convenient font size.

thanks much for the pointers

**Comment by jjallaire** [comment]
It's certainly possible that our default width isn't ideal. Let me know what you come up with and we can either evaluate changing our default or providing a top-level option for another layout variation. As I said there is another layout that comes into play at >= 1180px but this CSS wasn't currently visible. I've added it explicitly so that you can play with that as well:

https://github.com/radixpub/radix-r/blob/master/inst/rmarkdown/templates/radix_article/resources/distill.html#L178-L198
